# Generated by Django 5.2 on 2025-05-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True)),
                ('descuento_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendos', to='productos.producto')),
            ],
        ),
    ]
