# Generated by Django 5.2 on 2025-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('BICICLETA', 'Bicicleta'), ('ACCESORIO', 'Accesorio')], max_length=15)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('rodado', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_accesorio', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
