# Generated by Django 5.2 on 2025-06-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_estado_productoimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("RESERVADO", "Reservado"),
                    ("EN_REPARACION", "En reparación"),
                    ("NO_DISPONIBLE", "No disponible"),
                ],
                default="DISPONIBLE",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProductoImagen",
        ),
    ]
