# Generated by Django 5.2 on 2025-06-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_producto_estado_delete_productoimagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(blank=True, null=True, verbose_name="Imagen (URL)"),
        ),
    ]
