# Generated by Django 5.2 on 2025-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_cliente', models.CharField(choices=[('TODOS', 'Todos'), ('CLIENTE', 'Cliente'), ('TECNICO', 'Técnico'), ('VENDEDOR', 'Vendedor'), ('SUPERVISOR', 'Supervisor')], default='TODOS', max_length=15)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='productos.producto')),
            ],
        ),
    ]
